import Head from 'next/head'
import axios from 'axios';
import { useState, useEffect, useRef } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [triggered, setTriggered] = useState(false);
  const initialRender = useRef(true);

  useEffect(() => {
    if (initialRender.current) {
      initialRender.current = false;
    } else {
      axios
        .get('./api/logger')
        .catch(err => console.log(err));
    }
  }, [triggered])

  return (
    <div className={styles.container}>
      <Head>
        <title>EKS Logging Workshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to EKS Logging <a href="https://workshops.aws/">Workshop!</a>
        </h1>

        <p className={styles.description}>
          Click the {' '}
          <code className={styles.code}>Random Log Generator</code>
          {' '} button below to generate random JSON logs. This will generate a random JSON log data every second for 10 minutes.
          Once the job is done, the site will bring the user back to the main page.
        </p>

        <div className={styles.grid}>
          {!triggered
            ?
            <div className={styles.card} onClick={() => setTriggered(true)}>
              <h2>Random Log Generator &rarr;</h2>
              <p>Click on this button to initiate the random JSON logger.</p>
            </div>
            :
            <div className={styles.card}>
              <h2>Random Log Generator &rarr;</h2>
              <p>Random log generator has been initiated! Random JSON log data will be sent every second for 10 minutes.
                TBD IDEA: Have a bar that shows how much time is left for the log generator to finish its job.</p>
            </div>
          }
        </div>

        {/* <div className={styles.grid}>
          <a href="/logger" className={styles.card}>
            <h2>Random Log Generator &rarr;</h2>
            <p>Click on this button to initiate the random JSON logger.</p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        Find this app @github/madebybk/eksworkshop
      </footer>
    </div>
  )
}
