import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [submitted, setSubmitted] = useState(false);
  const [logFreq, setLogFreq] = useState(0);
  const [logDuration, setLogDuration] = useState(0);

  const handleSubmit = async (event) => {
    event.preventDefault();

    // Get data from the form
    const data = {
      numLogs: event.target.numLogs.value,
      duration: event.target.duration.value,
    };

    // Send the data in a JSON format
    const JSONdata = JSON.stringify(data);
    const endpoint = '/api/log_generator';
    const options = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSONdata,
    };
    const res = await fetch(endpoint, options);
    const result = await res.json();

    // Update State
    setLogFreq(data.numLogs)
    setLogDuration(data.duration)
    setSubmitted(true)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>EKS Logging Workshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Random Log Generator </h1>
        <h1 className={styles.title}>EKS <a href="https://madebybk.gitbook.io/eks-observability-workshop/">Workshop</a></h1>
        <p className={styles.description}>
          Select the frequency and duration of the logs, and click the submit button on {' '}
          <code className={styles.code}>Random JSON Logger</code>
          {' '} below to generate random JSON logs.
        </p>
        <div className={styles.grid}>
          {!submitted
            ?
            <div className={styles.card}>
              <h2>Random JSON Logger &rarr;</h2>
              <form action="/api/log_generator" method="post" onSubmit={handleSubmit}>
                <label htmlFor="numLogs">Records per second: </label>
                <select id="numLogs" name="numLogs" required="required" className={styles.dropdown}>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
                  <option value="20">20</option>
                  <option value="30">30</option>
                  <option value="40">40</option>
                  <option value="50">50</option>
                  <option value="60">60</option>
                  <option value="70">70</option>
                  <option value="80">80</option>
                  <option value="90">90</option>
                  <option value="100">100</option>
                  <option value="200">200</option>
                  <option value="300">300</option>
                  <option value="400">400</option>
                  <option value="500">500</option>
                  <option value="600">600</option>
                  <option value="700">700</option>
                  <option value="800">800</option>
                  <option value="900">900</option>
                  <option value="1000">1000</option>
                  <option value="2000">2000</option>
                  <option value="3000">3000</option>
                  <option value="4000">4000</option>
                  <option value="5000">5000</option>
                  <option value="6000">6000</option>
                  <option value="7000">7000</option>
                  <option value="8000">8000</option>
                  <option value="9000">9000</option>
                  <option value="10000">10000</option>
                </select>
                <label htmlFor="duration">Duration of the logs: </label>
                <select id="duration" name="duration" required="required" className={styles.dropdown}>
                  <option value="1">1 minute</option>
                  <option value="2">2 minutes</option>
                  <option value="3">3 minutes</option>
                  <option value="4">4 minutes</option>
                  <option value="5">5 minutes</option>
                  <option value="6">6 minutes</option>
                  <option value="7">7 minutes</option>
                  <option value="8">8 minutes</option>
                  <option value="9">9 minutes</option>
                  <option value="10">10 minutes</option>
                  <option value="20">20 minutes</option>
                  <option value="30">30 minutes</option>
                  <option value="40">40 minutes</option>
                  <option value="50">50 minutes</option>
                  <option value="60">60 minutes</option>
                  <option value="90">90 minutes</option>
                  <option value="120">120 minutes</option>
                </select>
                <button type="submit" className={styles.submit}>Submit</button>
              </form>
            </div>
            :
            <div className={styles.card}>
              <h2>Random JSON Logger &rarr;</h2>
              <p>Random log generator has been initiated! Random JSON log data will be sent <b>{logFreq} time{logFreq > 1 ? 's' : ''} per second</b> for <b>{logDuration} minute{logDuration > 1 ? 's' : ''}.</b></p>
            </div>
          }
        </div>
      </main>

      <footer className={styles.footer}>
        Find this app @ github.com/madebybk/nextjs-random-logger
      </footer>
    </div>
  )
}
